DROP TABLE IF EXISTS episode;
DROP TABLE IF EXISTS log;
DROP TABLE IF EXISTS program;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS subscribed;
DROP TABLE IF EXISTS torrent_site;
DROP TABLE IF EXISTS user;
